TinyMCE: Add media_button parameter
siteorigin/so-widgets-bundle pull request #1229
Opened 2021-01-06 08:25 UTC by AlexGStapleton

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/903

2021-01-18 01:07 UTC, AlexGStapleton commented
To test this open so-widgets-bundle/widgets/editor/editor.php and replace:

'title' => array(
	'type' => 'text',
	'label' => __('Title', 'so-widgets-bundle'),
),

With:

```
'title' => array(
	'type' => 'text',
	'label' => __('Title', 'so-widgets-bundle'),
	'media_buttons' => false,
),
```

2021-01-18 03:19 UTC, AlexGStapleton commented
Sorry, there was a typo in the previously provided test code. Please switch to the updated code.

2021-03-04 12:36 UTC, Misplon approved these changes

2021-03-30 09:47 UTC, gregpriday requested changes
Looks like there's some test code.

2021-03-30 09:47 UTC, gregpriday commented on base/inc/fields/tinymce.class.php
> +		test="123"
I assume this test code shouldn't be here?

2021-04-06 12:28 UTC, gregpriday approved these changes

2021-04-24 15:14 UTC, merged