Improve Measurement field spacing for more consistent field sizing/padding
siteorigin/so-widgets-bundle pull request #1263
Opened 2021-03-29 19:36 UTC by AlexGStapleton

Related https://github.com/siteorigin/so-widgets-bundle/pull/1261#issuecomment-805142949

This PR ensures the measurement field is more consistently sized. It also prevents the unit from being clipped due to a smaller than intended line-height (this is visible in the linked comment).

This affects both the Block Editor and Classic Editor.
This PR is compatible with #1261.

2021-04-06 12:32 UTC, Misplon commented
Thanks, mate. This looks to have negatively impacted the measurement unit select field.

Classic Editor:
<img width="276" alt="classic" src="https://user-images.githubusercontent.com/789159/113711028-be0a7b80-96e4-11eb-891e-009ac7f30772.png">

Block Editor:
<img width="492" alt="block" src="https://user-images.githubusercontent.com/789159/113711213-f6aa5500-96e4-11eb-9e4e-35dccc66705b.png">

2021-04-06 16:40 UTC, Misplon requested changes
Looking good, just need to resolve the measurement select field alignment.

2021-04-06 20:58 UTC, AlexGStapleton commented
I'm unable to replicate the mentioned field alignment while using this PR. [Here's a build](https://drive.google.com/uc?id=1RIVe2IVd_F2ifIXoeMubXy83H-9XDc6c) of this PR that I've double checked works for me.

2021-04-07 09:42 UTC, Misplon commented
Thanks, mate. I've sent a screenshot and screencast in Slack using this build.

2021-04-07 10:47 UTC, AlexGStapleton commented
How does that look?

2021-04-07 12:46 UTC, Misplon commented
Looks good.

2021-04-07 12:46 UTC, Misplon approved these changes

2021-04-07 12:47 UTC, merged