Base Carousel Widget
siteorigin/so-widgets-bundle pull request #1265
Opened 2021-04-06 10:11 UTC by AlexGStapleton

This is the foundation of https://github.com/siteorigin/so-widgets-bundle/issues/1111

- Styling of navigation is left up to the widget. With that said, it's likely to be expanded in future commits/PR.
- Breakpoint changes will be covered in the next commit.

In hindsight, the Post Carousel Commit could have been spun off into a separate PR as it does exceed the scope of the title of the PR. Having it in this PR does however make it much easier to test. The Anything Carousel will definitely be in a separate PR.

2021-04-14 16:58 UTC, AlexGStapleton commented
@Misplon Regarding the responsive settings, it makes sense to add a copy of all of the global widget settings. What are your thoughts on doing that? If you're keen, how do you want to handle the widget specific responsive settings? We could handle the fields like page builder and have an empty field mean the default value is used.

2021-04-14 17:14 UTC, Misplon commented
Sounds good. If we could add in placeholder support though, that would be ideal vs blank fields when the default is being used.

2021-04-14 18:27 UTC, AlexGStapleton commented
The last commit adds global responsive fields. It uses placeholders when the user is editing widgets to prevent the global settings from being saved.

`get_breakpoints()` is present to allow for continued support of the `siteorigin_widgets_post_carousel_breakpoints` filter. You can use the following code to confirm that filter still works as expected:

add_filter( 'siteorigin_widgets_post_carousel_breakpoints', function( $breakpoints ) {
	return array(
		'tablet_landscape' => 333,
		'tablet_portrait'  => 222,
		'mobile'           => 111,
	);
} );

A global `siteorigin_widgets_carousel_breakpoints` filter doesn't have a use case due to the responsive settings now being editable via widget settings. @Misplon If you're keen though, I can add that filter.

2021-04-15 08:32 UTC, Misplon commented
Thanks, mate. We can add that filter at some point if we get a request.

2021-06-03 14:11 UTC, Misplon approved these changes

2021-06-03 14:11 UTC, Misplon commented
@AlexGStapleton Can you take a look at the above conflict? Thanks, mate.

2021-06-22 20:03 UTC, AlexGStapleton commented
@Misplon The last two commits could result in the Post Carousel styling not working as expected so re-testing will be required.

2021-07-07 16:27 UTC, gregpriday requested changes

2021-07-07 16:27 UTC, gregpriday commented on base/inc/widgets/base-carousel.class.php
> +	// Allow widgets to override settings.
Same here, just need to stick to using PHPDoc format.

2021-07-09 11:50 UTC, gregpriday approved these changes

2021-07-09 11:54 UTC, Misplon commented
@AlexGStapleton Just a small conflict here, thanks mate.

2021-07-09 17:16 UTC, merged