Post Selector: Add option to adjust taxonomies relationship
siteorigin/so-widgets-bundle pull request #1321
Opened 2021-05-31 16:50 UTC by AlexGStapleton

This PR will add a new setting to the posts form field that will allow users to change the taxonomy relationship. Previously, it was only possible to adjust the taxonomies relationship by using the `siteorigin_widgets_posts_selector_query` hook.

2021-05-31 18:33 UTC, Misplon commented on base/inc/fields/posts.class.php
> +				'label' => __( 'Taxonomies Relationship', 'so-widgets-bundle' ),
Perhaps `Taxonomies relationship` to match case.

2021-05-31 18:43 UTC, Misplon commented on base/inc/fields/posts.class.php
> +				'description' => __( 'The relationship between the taxonomies. AND requires posts to have all of the specified taxonomies, while OR requires posts to have at least one of the specified taxonomies
How about `The relationship between taxonomies. AND requires posts to have all of the specified taxonomies. OR requires posts to have at least one of the specified taxonomies.`

2021-05-31 18:49 UTC, Misplon requested changes
Minor label changes requested, otherwise working great.

2021-06-03 10:15 UTC, Misplon approved these changes

2021-06-10 08:19 UTC, gregpriday approved these changes

2021-06-10 10:48 UTC, merged