Preset Form Field Adjustments
siteorigin/so-widgets-bundle pull request #1356
Opened 2021-06-27 22:16 UTC by AlexGStapleton

-Preset Field: Store Selected Preset
This commit allows for the selected preset to be saved.

- Preset: Add `default_preset` to allow default Preset 
This commit allows the preset field to support a default preset. This change was complicated due to how state emitters work.
The `default_preset ` parameter was used over `default` due to how `default` being a valid form field option and it not allowing for reliable default detection in the preset JS.

- SiteOrigin Widget: dynamic_preset_state_handler 

This commit allows a method of dynamically setting the state_handler for an an array of fields based on the values used by the preset field. This basically means, we can easily show/hide fields based on the preset values. This is going to be used heavily by some of our upcoming widgets. 

Posting a test widget shortly.

2021-06-27 22:24 UTC, AlexGStapleton commented
@Misplon Where do you want to put the "SiteOrigin Widget: dynamic_preset_state_handler" documentation? Adding it to the Form Field, or State Emitters page is a bit much as it's quite specific. Maybe a new page under the Advanced Concepts?

2021-06-28 19:43 UTC, Misplon commented
@AlexGStapleton Thanks, mate. Sure, let's go with Advanced Concepts. Is it a concept though? Advanced Functionality?

2021-06-28 23:37 UTC, AlexGStapleton commented
I don't think we should introduce a new section called Advanced Functionality, but I would be okay with renaming Advanced Concepts to Advanced Functionality.

2021-06-30 16:17 UTC, Misplon commented
Ahh my bad, I misread that. Got you. Please, proceed as discussed.

2021-06-30 19:34 UTC, Misplon commented
@AlexGStapleton Thanks, mate. The only item that isn't working for me is:

* That the default_preset "test-2" is loaded by default.

2021-07-01 21:20 UTC, AlexGStapleton commented
It appears there was an issue with the initial PR test plugin. Please try [the preset docs version of that plugin](https://siteorigin.com/wp-content/uploads/2021/06/siteorigin-preset-field-demo.zip) instead. I've tested and confirmed that works for me. I've updated the installation instructions in the initial issue.

2021-07-02 11:00 UTC, Misplon commented
Awesome. Super cool.

2021-07-02 11:01 UTC, Misplon approved these changes

2021-07-06 01:55 UTC, AlexGStapleton commented
The last commit is a pretty significant rework to allow for better handling of section fields.

To test it please use the test plugin to test existing functionality and https://github.com/siteorigin/so-widgets-bundle/pull/1359/commits/044089a0a2fd94accd38d12eeda1dae1154e3a6f to test section support - the column count field in the settings section will change and disappear based on the selected template.

No documentation changes are required.

2021-07-06 13:46 UTC, Misplon approved these changes

2021-07-06 13:46 UTC, Misplon commented
Awesome, nicely done mate.

2021-07-07 16:19 UTC, gregpriday requested changes
Just a change to comments.

2021-07-07 16:19 UTC, gregpriday commented on base/siteorigin-widget.class.php
> +	// Add state_handler for fields based on how they're adjusted by preset data.
For these comments, can we go with a PHPDoc format rather.

2021-07-09 11:53 UTC, gregpriday approved these changes

2021-07-09 11:54 UTC, merged