Add Missing Carousel Changes
siteorigin/so-widgets-bundle pull request #1364
Opened 2021-07-13 10:26 UTC by AlexGStapleton

Something went wrong during the conflict fix of https://github.com/siteorigin/so-widgets-bundle/pull/1265  which resulted in some files being excluded from the develop merge. This PR restores those files.

Please test both the Anything Carousel and Post Carousel widgets.

2021-07-13 11:43 UTC, Misplon commented on base/inc/widgets/tpl/carousel.php
> +	     foreach( $settings['attributes'] as $n => $v ) {
Can we make this `foreach (` ?

2021-07-13 11:54 UTC, Misplon requested changes
Minor spacing request, otherwise, all seems fine.

2021-07-13 15:43 UTC, Misplon approved these changes

2021-07-14 10:54 UTC, gregpriday approved these changes

2021-07-14 10:54 UTC, merged